domain_path: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/arm_core_platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /media/bartek/LEXAR/DEV/FPGA/Xylinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
