# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/arm_core/arm_core.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_core || ORIG_REF_NAME==arm_core} -quiet] -quiet

# IP: bd/arm_core/ip/arm_core_processing_system7_0_0/arm_core_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_core_processing_system7_0_0 || ORIG_REF_NAME==arm_core_processing_system7_0_0} -quiet] -quiet

# IP: bd/arm_core/ip/arm_core_axi_gpio_0_0/arm_core_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_core_axi_gpio_0_0 || ORIG_REF_NAME==arm_core_axi_gpio_0_0} -quiet] -quiet

# IP: bd/arm_core/ip/arm_core_axi_smc_0/arm_core_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_core_axi_smc_0 || ORIG_REF_NAME==arm_core_axi_smc_0} -quiet] -quiet

# Block Designs: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/bd_302c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_1/bd_302c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_2/bd_302c_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_3/bd_302c_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_4/bd_302c_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_5/bd_302c_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_6/bd_302c_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_7/bd_302c_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_8/bd_302c_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_9/bd_302c_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_10/bd_302c_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_11/bd_302c_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_12/bd_302c_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_13/bd_302c_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_14/bd_302c_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_15/bd_302c_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_16/bd_302c_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_17/bd_302c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_18/bd_302c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_19/bd_302c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_20/bd_302c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_21/bd_302c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_22/bd_302c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_23/bd_302c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_24/bd_302c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_25/bd_302c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_26/bd_302c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_27/bd_302c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_28/bd_302c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_29/bd_302c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_30/bd_302c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_31/bd_302c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_32/bd_302c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_33/bd_302c_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_34/bd_302c_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_35/bd_302c_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_36/bd_302c_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_37/bd_302c_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_38/bd_302c_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_39/bd_302c_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/arm_core/ip/arm_core_rst_ps7_0_50M_0/arm_core_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_core_rst_ps7_0_50M_0 || ORIG_REF_NAME==arm_core_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/arm_core/ip/arm_core_top_0_3/arm_core_top_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_core_top_0_3 || ORIG_REF_NAME==arm_core_top_0_3} -quiet] -quiet

# IP: bd/arm_core/ip/arm_core_axi_gpio_1_0/arm_core_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_core_axi_gpio_1_0 || ORIG_REF_NAME==arm_core_axi_gpio_1_0} -quiet] -quiet

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_processing_system7_0_0/arm_core_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==arm_core_processing_system7_0_0 || ORIG_REF_NAME==arm_core_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_gpio_0_0/arm_core_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==arm_core_axi_gpio_0_0 || ORIG_REF_NAME==arm_core_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_gpio_0_0/arm_core_axi_gpio_0_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_1/bd_302c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_2/bd_302c_arinsw_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_3/bd_302c_rinsw_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_4/bd_302c_awinsw_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_5/bd_302c_winsw_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_6/bd_302c_binsw_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_7/bd_302c_aroutsw_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_8/bd_302c_routsw_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_9/bd_302c_awoutsw_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_10/bd_302c_woutsw_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_11/bd_302c_boutsw_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_12/bd_302c_arni_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_13/bd_302c_rni_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_14/bd_302c_awni_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_15/bd_302c_wni_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_16/bd_302c_bni_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_20/bd_302c_s00a2s_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_21/bd_302c_sarn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_22/bd_302c_srn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_23/bd_302c_sawn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_24/bd_302c_swn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_25/bd_302c_sbn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_26/bd_302c_m00s2a_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_27/bd_302c_m00arn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_28/bd_302c_m00rn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_29/bd_302c_m00awn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_30/bd_302c_m00wn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_31/bd_302c_m00bn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_33/bd_302c_m01s2a_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_34/bd_302c_m01arn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_35/bd_302c_m01rn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_36/bd_302c_m01awn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_37/bd_302c_m01wn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/bd_0/ip/ip_38/bd_302c_m01bn_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==arm_core_axi_smc_0 || ORIG_REF_NAME==arm_core_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_rst_ps7_0_50M_0/arm_core_rst_ps7_0_50M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==arm_core_rst_ps7_0_50M_0 || ORIG_REF_NAME==arm_core_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_gpio_1_0/arm_core_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==arm_core_axi_gpio_1_0 || ORIG_REF_NAME==arm_core_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/ip/arm_core_axi_gpio_1_0/arm_core_axi_gpio_1_0_ooc.xdc

# XDC: /media/bartek/LEXAR/SUT/SoC/Projekt-LED-Matrix-Clock/SoC-LED-Clock/SoC-LED-Clock.gen/sources_1/bd/arm_core/arm_core_ooc.xdc
